server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/choehagjun/works/work-space/spring-cloud-example/application-configs      # 맥북 경로
          uri: file://C:\git-repo\spring-cloud-example\application-configs                              # 데스크탑 경로

