server:
  port: 8001

eureka:
  client:
    fetch-registry: false        # Eureka????? ?????? ??? ????? ??? ???? ???? ??, true? ???? ??? ??? ???? ?????.
    register-with-eureka: false
spring:
  application:
    name: my-first-service